<a href="https://colab.research.google.com/github/sbhusal123/scientific-programming/blob/main/Numpy_Multidimension.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import matplotlib.pyplot as plt

# Creating 2d DImension Array

As a list of list of numbers

In [33]:
a1 = np.array([[1,2,3], [4, 5, 6]]) # 2 dimensional array
a1

array([[1, 2, 3],
       [4, 5, 6]])

Zeros: Pass the size of an array as a tuple: (row, cols)

In [34]:
a2 = np.zeros((2,3))
a2

array([[0., 0., 0.],
       [0., 0., 0.]])

Ones: Similar to arrays of zero.

In [35]:
a3 = np.ones((3,3))
a3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Random 2d arrays. Generated using pesudo random number generation algorithm.

In [36]:
a4 = np.random.random((2,2))
a4

array([[0.52369307, 0.11808162],
       [0.57067978, 0.51288428]])

Random. Generation from gaussian / normal distribution.
**Pass the size directly.**


In [37]:
a5 = np.random.randn(100, 100)
mean = np.mean(a5) # np.mean(np.ravel(a5))
std = np.std(a5)
print("Mean = {}".format(mean))
print("Std = {}".format(std))

Mean = -0.007759014988978384
Std = 1.0023179270259632


2d array to 1d array

In [38]:
x = np.array([[1, 2], [3, 4]])
x.ravel()

array([1, 2, 3, 4])

# 2d Dimension Array Operations