<a href="https://colab.research.google.com/github/sbhusal123/scientific-programming/blob/main/Vector_Analysis_and_Co_ord_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Transformation

**i. From Spherical to Rectangular:**

$\begin{bmatrix}
 A_x \\ A_y \\ A_z
 \end{bmatrix} =
\begin{bmatrix}
sin(\theta)cos(\phi) & cos(\theta)cos(\phi) & -sin(\phi) \\
sin(\theta)sin(\phi) & cos(\theta)sin(\phi) & cos(\phi) \\
cos(\theta) & -sin(\theta) & 0
\end{bmatrix}
*
\begin{bmatrix}
 A_r \\ A_{\theta} \\ A_{\phi}
\end{bmatrix}
$

> For inverse transformation take transpose of trans matrix

**ii. From Cylindrical to Rectangular:**

$\begin{bmatrix}
 A_x \\ A_y \\ A_z
 \end{bmatrix} =
\begin{bmatrix}
cos(\phi) & -sin(\phi) & 0 \\
sin(\phi) & cos(\phi) & 0 \\
0 & 0 & 1
\end{bmatrix}
*
\begin{bmatrix}
 A_{\rho} \\ A_{\phi} \\ A_{z}
\end{bmatrix}
$

> For inverse transformation take transpose of trans matrix

**iii. From Cylindrical to Spherical:**

$\begin{bmatrix}
 A_r \\ A_{\theta} \\ A_{\phi}
 \end{bmatrix} =
\begin{bmatrix}
sin(\theta) & 0 & cos(\theta) \\
cos(\theta) & 0 & -sin(\theta) \\
0 & 1 & 0
\end{bmatrix}
*
\begin{bmatrix}
 A_{\rho} \\ A_{\phi} \\ A_{z}
\end{bmatrix}
$

> For inverse transformation take transpose of trans matrix

**Note: All the angles are in radian.**

In [1]:
import numpy as np
import scipy as spy

**Example 1**

If $\vec{A}=3\hat{a_r}+2\hat{a_\theta}-6\hat{a_\phi}$ and $\vec{B}=4\hat{a_r}+3\hat{a_\phi}$, determine:

i. $\vec{A}.\vec{B}$

ii. $\vec{A}\times\vec{B}$

iii. The vector component of $\vec{A}$ along $\hat{a_z}$ at $(1, \frac{\pi}{3}, \frac{5\pi}{3})$

In [2]:
# Define A vector as numpy array
A = np.array([3, 2, -6])
B = np.array([4, 0, 3])

In [3]:
# i: Dot product
a_dot_b = np.dot(A, B)
print(a_dot_b)

-6


In [4]:
# ii. Cross product
a_cross_b = np.cross(A, B)
print(a_cross_b)

[  6 -33  -8]


$\vec{A}$ along $\hat{a_z}$ is given by $(A.\hat{a_z}).\hat{a_z}$

i.e. (Magnitude of projection).Unit Vector


In [5]:
# ii. Vector component
A_sph = np.array([3, 2, -6])
p = np.array([1, np.pi/3, 5*np.pi/4]) # at sph co-ord
r = p[0]
theta = p[1]
phi = p[2]

# Conversion matrix from spherical to rectangular
sp_to_rect = np.array([
                        [np.sin(theta)*np.cos(phi), np.cos(theta)*np.cos(phi), -np.sin(phi)],
                        [np.sin(theta)*np.sin(phi), np.cos(theta)*np.sin(phi), np.cos(phi)],
                        [np.cos(theta), -np.sin(theta), 0]
                        ])

# Into rect co-ord
a_rect = sp_to_rect.dot(A_sph)
a_rect_z = a_rect[2]

# projection / along az
sp_to_rect_z = sp_to_rect[2]
along_az = a_rect_z * (sp_to_rect_z)
along_az

array([-0.1160254 ,  0.20096189, -0.        ])

# Example 2

Express the unit vector $\hat{a_x}$ in spherical component at $\rho=2.5,\phi=0.7rad,z=1.5$

In [6]:
# Unit vector
x = np.array([1, 0, 0])

at_cylindrical = (2.5, 0.7, 1.5)
rho = at_cylindrical[0]  ## radius
phi = at_cylindrical[1]
z = at_cylindrical[2]

r = np.sqrt(rho**2+z**2)
theta = np.arccos(z/r)
phi = phi

# Rectangular to sph transformation matrix
rect_to_sph = np.array([
                        [np.sin(theta)*np.cos(phi), np.cos(theta)*np.cos(phi), -np.sin(phi)],
                        [np.sin(theta)*np.sin(phi), np.cos(theta)*np.sin(phi), np.cos(phi)],
                        [np.cos(theta), -np.sin(theta), 0]
                        ]).T

in_sph = rect_to_sph.dot(x)
in_sph

array([ 0.65584676,  0.39350806, -0.64421769])

# Eample 3

Transform the vector:

(a) $\vec{A}=y\hat{a_x}+(x+y)\hat{a_z}$ at P(-2, 6, 3) in cylindrical system.

(b) $\vec{A}=3\hat{a_\rho}-\hat{a_\phi}$ at Q(3, 4, -1) in cartesian co-ordinate system.

In [26]:
# a
p = np.array([-2, 6, 3]) # at point
x = p[0]
y = p[1]
z = p[2]

A = np.array([y, 0, x+y])

# p in cylindrical coordinate system
rho = np.sqrt(x**2+y**2)
phi = 2*np.pi-np.arctan(np.abs(6/2))
z = z

rect_to_cyl = np.array([
                        [np.cos(phi), -np.sin(phi), 0],
                        [np.sin(phi), np.cos(phi), 0],
                        [0, 0, 1]
]).T

a_cyl = rect_to_cyl@A
a_cyl

array([1.8973666 , 5.69209979, 4.        ])

In [27]:
# b
A = np.array([3, -1, 0]) # in cyl co-ord

# at point
q = np.array([3, 4, -1]) # in rect co-ord

x = q[0]
y = q[1]
z = q[2]

# q in terms of sph co-ord
rho = np.sqrt(x**2+y*2)
phi = np.arctan(np.abs(y/x))
z = z

cyl_to_rect = np.array([
                        [np.cos(phi), -np.sin(phi), 0],
                        [np.sin(phi), np.cos(phi), 0],
                        [0, 0, 1]
])

a_rect = rect_to_cyl@A
a_rect

array([1.8973666 , 2.52982213, 0.        ])

# Example 7

Transform $\vec{A_c}=x\hat{a_x}+xy\hat{a_z}$ at point (1, 2, 3) in cartesian coordinates system to $\vec{A_{cy}}$ in cylindrical system.

In [28]:
# at point in cartesian
p = np.array([1, 2, 3])
x = p[0]
y = p[1]
z = p[2]

A = np.array([x, 0, x*y])

# p in cyl
r = np.sqrt(x**2+y**2)
phi = np.arctan(y/x)
z = z

rect_to_cyl = np.array([
                        [np.cos(phi), -np.sin(phi), 0],
                        [np.sin(phi), np.cos(phi), 0],
                        [0, 0, 1]
]).T

a_cyl = rect_to_cyl@A
a_cyl

array([ 0.4472136 , -0.89442719,  2.        ])

# Example 9

Transform vector $\vec{A}=rcos(\phi)\hat{a_r}+z\hat{a_z}$ at point $(1, 30^{o}, 2)$ in cylindrical co-ord system to a vector in spherical co-ord system.

In [30]:
# at point in cyl
p = np.array([1, np.deg2rad(30), 2])
rho = p[0]
phi = p[1]
z = 2

A = np.array([rho*np.cos(phi), 0, z])

# p in shp
r = np.sqrt(rho**2+z**2)
theta = np.arccos(z/r)
phi = phi

cyl_to_sph = np.array([
                       [np.sin(theta), 0, np.cos(theta)],
                       [np.cos(theta), 0, -np.sin(theta)],
                       [0, 1, 0]
])

A_sph = cyl_to_sph@A
A_sph

array([ 2.17615272, -0.11983052,  0.        ])

# Example 10
Express a scalar potential field $V=x^2+2y^2+3z^2$ in spherical coord at $P(2, 60^o, 90^o)$.

In [33]:
# at p in spherical
p = np.array([2, np.deg2rad(60), np.deg2rad(90)])
r = p[0]
theta = p[1]
phi = p[2]

# P in rectangular
x = r*np.sin(theta)*np.cos(phi)
y = r*np.sin(theta)*np.sin(phi)
z = r*np.cos(theta)

# Scalar field
V = x**2+2*y**2+3*z**2

V

9.0

# Example 11

Express in cartesin components:

i. The vector at $A(\rho=4, \phi=40^o, z=-2)$ that extends to $B(\rho=5, \phi=-110^o, z=2)$

ii. A unit vector at B directed to A

In [43]:
# i.

# A in cyl
A = np.array([4, np.deg2rad(40), -2])
A_r = A[0]
A_phi = A[1]
A_z = A[2]

# B in cyl
B = np.array([5, np.deg2rad(-110), 2])
B_r = B[0]
B_phi = B[1]
B_z = B[2]

A_cyl_to_rect = np.array([
                   [np.cos(A_phi), 0, 0],
                   [np.sin(A_phi),0, 0],
                   [0, 0, 1]
                   ])
A_rect = A_cyl_to_rect@A

B_cyl_to_rect = np.array([
                   [np.cos(B_phi), 0, 0],
                   [np.sin(B_phi), 0, 0],
                   [0, 0, 1]
                   ])
B_rect = B_cyl_to_rect@B

AB_rect = B_rect - A_rect
AB_rect

array([-4.77427849, -7.26961354,  4.        ])

In [45]:
# 2:
BA = A_rect - B_rect

# magnitude of BA
BA_mag = np.sqrt(BA.dot(BA))

BA_unit = BA/BA_mag
BA_unit

array([ 0.49872691,  0.75939263, -0.41784484])